### PR TITLE
Clarify YAML structure for service specific secrets.

### PR DESCRIPTION
**Pull request by tmigone**
Change-type: patch
Signed-off-by: Tomás Migone <tomas@balena.io>

### CODE REVIEW

**Comment by tmigone** [comment]
I think it failed because i didn't initially add <> to the Signed-off-by email.

**Comment by tmigone** [comment]
Any idea why it's failing? ResinCI logs say "Error: Commit body should not contain footer tags" but i can't see why.

**Comment by hedss** [comment]
Hi @tmigone 

I've just realised a couple of reasons why this isn't working.

We normally work on branches of the repo we're going to change. So in this case, you need to create a new branch in this repo, and make your changes there.

Secondly, the commit needs to include a body. That can actually be an empty line, but it does have to exist between the heading and the footer, eg.:

```
This is a fix of mine.

Change-type: patch
Signed-off-by: someone
```

**Comment by tmigone** [comment]
Closed, see [here](https://github.com/balena-io-projects/balena-cli-masterclass/pull/9) for new PR.

**Pull request closed without merging**
